development:
  adapter: postgresql
  encoding: unicode
  database: rest_example_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: rest_example_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rest_example_production
  pool: 5
  username:
  password:
